server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://106.15.62.222:3306/zentao?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true